- id: lint-dependency-groups
  name: "Check '[dependency-groups]' in pyproject.toml"
  description: 'Read all Dependency Groups and validate that their contents can resolve'
  entry: lint-dependency-groups
  language: python
  types: toml
  files: ^pyproject\.toml$
