name: build
on:
  push:
  pull_request:

jobs:
  run-tox-env:
    strategy:
      matrix:
        toxenv: [mypy, twine-check]
        py: ["3.x"]

    runs-on: ubuntu-latest
    name: "Run '${{ matrix.toxenv }}' on python ${{ matrix.py }}"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.py }}"

      - uses: astral-sh/setup-uv@v3

      - run: uv tool install tox --with tox-uv

      - run: tox run -e "${{ matrix.toxenv }}"

  ci-test-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: "Run tests on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: |
            3.8
            3.9
            3.10
            3.11
            3.12
            3.13

      - uses: astral-sh/setup-uv@v3

      - run: uv tool install tox --with tox-uv

      - name: test
        run: tox run -m ci
