name: build
on:
  push:
  pull_request:

jobs:
  run-tox-env:
    strategy:
      matrix:
        toxenv: [mypy, twine-check]

    runs-on: ubuntu-latest
    name: "Run '${{ matrix.toxenv }}'"
    steps:
      - uses: actions/checkout@v4

      # get the week of the year (1-52) for nice cache control
      - name: set .weeknum.txt
        run: /bin/date -u "+%U" > .weeknum.txt
        shell: bash

      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: ".weeknum.txt"

      - run: uv tool install tox --with tox-uv

      - run: tox run -e "${{ matrix.toxenv }}"

  ci-test-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: "Run tests on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      # get the week of the year (1-52) for nice cache control
      - name: set .weeknum.txt
        run: /bin/date -u "+%U" > .weeknum.txt
        shell: bash

      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: ".weeknum.txt"

      - name: install pythons
        run: uv python install 3.8 3.9 3.10 3.11 3.12 3.13

      - run: uv tool install tox --with tox-uv

      - name: test
        run: tox run -m ci
