name: build
on:
  push:
  pull_request:

jobs:
  run-tox-env:
    strategy:
      matrix:
        toxenv: [mypy, twine-check]
        py: ["3.x"]

    runs-on: ubuntu-latest
    name: "Run '${{ matrix.toxenv }}' on python ${{ matrix.py }}"
    steps:
      - uses: actions/checkout@v4

      - name: get date for caching
        run: /bin/date -u "+%U" > cachedate.txt
        shell: bash

      - uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.py }}"
          cache: "pip"
          cache-dependency-path: |
            .github/workflows/build.yaml
            pyproject.toml
            tox.ini
            cachedate.txt

      - run: python -m pip install tox

      - run: python -m tox run -e "${{ matrix.toxenv }}"

  ci-test-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: "Run tests on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: get date for caching
        run: /bin/date -u "+%U" > cachedate.txt
        shell: bash

      - uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: |
            3.8
            3.9
            3.10
            3.11
            3.12
            3.13
          cache: "pip"
          cache-dependency-path: |
            .github/workflows/build.yaml
            pyproject.toml
            tox.ini
            cachedate.txt

      - run: python -m pip install tox

      - name: cache tox virtualenvs
        uses: actions/cache@v4
        with:
          path: .tox
          key: >
            tox
            os=${{ runner.os }}
            python=${{ steps.setup-python.outputs.python-version }}
            hash=${{ hashFiles('.github/workflows/build.yaml', 'pyproject.toml', 'tox.ini', 'cachedate.txt') }}

      - name: test
        run: |
          python -m tox run -m ci
